export const iconMap = {
  backArrow: '/icons/back-arrow.svg',
  kebab: '/icons/kebab.svg',
  empty: '/icons/empty.svg',
  addAPhoto: '/icons/add_a_photo.svg',
  check: '/icons/check.svg',
  me: '/icons/me.svg',
  arrowDropDown: '/icons/arrow_drop_down.svg',
  filerList: '/icons/filter_list.svg',
  myProduct: '/icons/my_product.svg',
  logo: '/icons/logo.svg',
  home: '/icons/home.svg',
  chat: '/icons/chat.svg',
  accountCircle: '/icons/account_circle.svg',
};
