export const iconMap = {
  backArrow: 'src/components/icons/back-arrow.svg',
  kebab: 'src/components/icons/kebab.svg',
  empty: 'src/components/icons/empty.svg',
  addAPhoto: '../../src/components/icons/add_a_photo.svg',
  check: 'src/components/icons/check.svg',
  me: 'src/components/icons/me.svg',
  arrowDropDown: '../../src/components/icons/arrow_drop_down.svg',
  filerList: '../../src/components/icons/filter_list.svg',
  myProduct: '../../src/components/icons/my_product.svg',
  logo: '../../src/components/icons/logo.svg',
  home: '@/src/components/icons/home.svg',
  chat: 'src/components/icons/chat.svg',
  accountCircle: 'src/components/icons/account_circle.svg',
};
